<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>RenpyRehost</AssemblyName>
    <RootNamespace>RenpyRehost.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <Version>0.0.1</Version>
    <Product>Ren'Py Rehost</Product>
    <AssemblyTitle>Ren'Py Rehost</AssemblyTitle>
    <RuntimeIdentifier Condition="'$(PublishSingleFile)' == 'true'">win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RenpyRehost.Core\RenpyRehost.Core.csproj" />
  </ItemGroup>

</Project>
